[package]
name = "moondust-kernel"
version = "0.0.3"
authors = ["Vinay Chandra Dommeti <moondust@vinay.vc>"]
edition = "2018"

[dependencies]
crossbeam-queue = { version = "0.3", default-features = false, features = ["alloc"] }
conquer-once = { version = "0.2", default-features = false }
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
lazy_static = { version = "1", features = ["spin_no_std"] }
linked_list_allocator = "0.8.6"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
spin = "0.7"
bitflags = "1.2"
elfloader = "0.11"
xmas-elf = "0.7"

# Text UI 
tui = { git = "https://github.com/vinaychandra/tui-rs", branch = "no_std" }

# RustType font support
rusttype = { version = "0.9", default-features = false, features = ["libm-math", "has-atomics"] }
libm = { version = "0.2.1", default-features = false }

[target.'cfg(target_arch = "x86_64")'.dependencies]
uart_16550 = "0.2.10"
x86_64 = "0.12.2"

[workspace]
members = [ "userspace/sigma_space" ]
default-members = [ ]

[dependencies.num-traits]
version = "0.2"
default-features = false
features = ["libm"]    # <--- Uncomment if you wish to use `Float` and `Real` without `std`
