[package]
name = "moondust-kernel"
version = "0.0.2"
authors = ["Vinay Chandra Dommeti <moondust@vinay.vc>"]
edition = "2018"

[dependencies]
rlibc = "1.0"
conquer-once = { version = "0.2", default-features = false }
lazy_static = { version = "1", features = ["spin_no_std"] }
linked_list_allocator = "0.8"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
spin = "0.5"
bitflags = "1.2"
elfloader = "0.10"
xmas-elf = "0.7"

[target.'cfg(target_arch = "x86_64")'.dependencies]
uart_16550 = "0.2"
x86_64 = "0.11"

[workspace]
members = [ "userspace/sigma_space" ]
default-members = [ ]
