[package]
name = "moondust-kernel"
version = "0.0.2"
authors = ["Vinay Chandra Dommeti <moondust@vinay.vc>"]
edition = "2018"

[dependencies]
rlibc = "1.0"

[target.'cfg(target_arch = "x86_64")'.dependencies]

[workspace]
members = [ "userspace/sigma_space" ]
default-members = [ ]
